// QUESTIONS
export const SET_DEFAULT_QUESTIONS = "SET_DEFAULT_QUESTIONS"
export const SET_QUESTION = "SET_QUESTION"

export const SEND_ANSWER_REQUEST =  "SEND_ANSWER_REQUEST"
export const SEND_ANSWER_SUCCESS =  "SEND_ANSWER_SUCCESS"
export const SEND_ANSWER_FAILED =  "SEND_ANSWER_FAILED"

export const SHOW_QUESTIONS_AGAIN_REQUEST =  "SHOW_QUESTIONS_AGAIN_REQUEST"
export const SHOW_QUESTIONS_AGAIN_SUCCESS =  "SHOW_QUESTIONS_AGAIN_SUCCESS"
export const SHOW_QUESTIONS_AGAIN_FAILED =  "SHOW_QUESTIONS_AGAIN_FAILED"

export const LEAVE_QUESTIONS = "LEAVE_QUESTIONS"
export const ENTER_QUIZ = "ENTER_QUIZ"

export const SEND_TRUE_ANSWER = "SEND_TRUE_ANSWER"
export const SEND_FALSE_ANSWER = "SEND_FALSE_ANSWER"

export const REFRESH_STATE = "REFRESH_STATE"

export const SET_LAST_QUESTION = "SET_LAST_QUESTION"
export const SET_LAST_QUESTION2 = "SET_LAST_QUESTION2"